#!/bbox/sh
#
# livecd_init:   this script have to be called at the system init,
#                to find the boot cd and to mount directories.
#                The best is to call it from /etc/rc.d/rc.S
#
# Author:	 Tomas Matejicek <http://www.slackware-live.org>

echo "USB stick boot icin 8 saniye bekleniyor."
sleep 8

. /bbox/mount_functions

# call mount_cd function, to mount /dev/hdc hdd etc.
#echo "Mounting all available CDs..."
mount_cds


#echo "mounting other discs..."
mount_all_discs

LIVECD_SUBDIR="`cat /proc/cmdline | egrep -io \"livecd_subdir=([-/.a-z0-9_]*)\"`"
LIVECD_SUBDIR="`echo \"$LIVECD_SUBDIR/\" | cut -b 15-`"
LIVECD_FIND="$LIVECD_SUBDIR"/bin.img

# look which directory is our CD
for DIR in /mnt/*
do
  if [ -r "$DIR/$LIVECD_FIND" ]; then
     export LIVECD_MOUNT="$DIR"
     export LIVECD_PATH=`dirname "$DIR/$LIVECD_FIND"`
     break
  fi
done

# if none, exit
if [ "${#LIVECD_PATH}" -lt 4 ]; then # there should be at least "/mnt"
  echo "cannot find your cram files!"
  #exit
  /box/sh
fi

# mount all images
